/*
 * NV20 PGRAPH renderer configuration (replaces xemu-config.h)
 */
#ifndef HW_NV20_PGRAPH_CONFIG_H
#define HW_NV20_PGRAPH_CONFIG_H

typedef enum {
    CONFIG_DISPLAY_RENDERER_NULL = 0,
    CONFIG_DISPLAY_RENDERER_OPENGL,
    CONFIG_DISPLAY_RENDERER_VULKAN,
    CONFIG_DISPLAY_RENDERER_METAL,
    CONFIG_DISPLAY_RENDERER__COUNT,
} CONFIG_DISPLAY_RENDERER;

#if defined(__APPLE__)
#define CONFIG_OPENGL 0
#define CONFIG_METAL 1
#define CONFIG_METAL_NATIVE 1
#else
#define CONFIG_OPENGL 1
#define CONFIG_METAL 0
#define CONFIG_METAL_NATIVE 0
#endif

#define CONFIG_VULKAN 0

#endif /* HW_NV20_PGRAPH_CONFIG_H */
